File change: CorsConfiguration C:\Project\Food-Fun>git pull origin main --rebase remote: Enumerating objects: 19, done. remote: Counting objects: 100% (19/19), done. remote: Compressing objects: 100% (7/7), done. remote: Total 10 (delta 3), reused 0 (delta 0), pack-reused 0 (from 0) Unpacking objects: 100% (10/10), 1.43 KiB | 27.00 KiB/s, done. From https://github.com/Nit02/Food-Fun  * branch            main       -> FETCH_HEAD    1af9198..a6eb55e  main       -> origin/main Auto-merging src/main/java/com/foodnfun/backend/config/CORSConfiguration.java CONFLICT (content): Merge conflict in src/main/java/com/foodnfun/backend/config/CORSConfiguration.java error: could not apply e0bed99... File change: CorsConfiguration hint: Resolve all conflicts manually, mark them as resolved with hint: "git add/rm <conflicted_files>", then run "git rebase --continue". hint: You can instead skip this commit: run "git rebase --skip". hint: To abort and get back to the state before "git rebase", run "git rebase --abort". Could not apply e0bed99... File change: CorsConfiguration
C:\Project\Food-Fun>git push origin main
To https://github.com/Nit02/Food-Fun.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/Nit02/Food-Fun.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you want to integrate the remote changes, use 'git pull'
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

C:\Project\Food-Fun>git pull origin main --rebase
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 10 (delta 3), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (10/10), 1.43 KiB | 27.00 KiB/s, done.
From https://github.com/Nit02/Food-Fun
 * branch            main       -> FETCH_HEAD
   1af9198..a6eb55e  main       -> origin/main
Auto-merging src/main/java/com/foodnfun/backend/config/CORSConfiguration.java
CONFLICT (content): Merge conflict in src/main/java/com/foodnfun/backend/config/CORSConfiguration.java
error: could not apply e0bed99... File change: CorsConfiguration
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply e0bed99... File change: CorsConfiguration

C:\Project\Food-Fun>git push origin main
To https://github.com/Nit02/Food-Fun.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/Nit02/Food-Fun.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you want to integrate the remote changes, use 'git pull'
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
C:\Project\Food-Fun>git pull origin main --rebase
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 10 (delta 3), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (10/10), 1.43 KiB | 27.00 KiB/s, done.
From https://github.com/Nit02/Food-Fun
 * branch            main       -> FETCH_HEAD
   1af9198..a6eb55e  main       -> origin/main
Auto-merging src/main/java/com/foodnfun/backend/config/CORSConfiguration.java
CONFLICT (content): Merge conflict in src/main/java/com/foodnfun/backend/config/CORSConfiguration.java
error: could not apply e0bed99... File change: CorsConfiguration
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply e0bed99... File change: CorsConfiguration

C:\Project\Food-Fun>git push origin main
To https://github.com/Nit02/Food-Fun.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/Nit02/Food-Fun.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you want to integrate the remote changes, use 'git pull'
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
C:\Project\Food-Fun>git pull origin main --rebase
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 10 (delta 3), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (10/10), 1.43 KiB | 27.00 KiB/s, done.
From https://github.com/Nit02/Food-Fun
 * branch            main       -> FETCH_HEAD
   1af9198..a6eb55e  main       -> origin/main
Auto-merging src/main/java/com/foodnfun/backend/config/CORSConfiguration.java
CONFLICT (content): Merge conflict in src/main/java/com/foodnfun/backend/config/CORSConfiguration.java
error: could not apply e0bed99... File change: CorsConfiguration
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply e0bed99... File change: CorsConfiguration

C:\Project\Food-Fun>git push origin main
To https://github.com/Nit02/Food-Fun.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/Nit02/Food-Fun.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you want to integrate the remote changes, use 'git pull'
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.